base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('post/<slug:slug>/', views.post, name="post"),
    path('profile/', views.profile, name="profile"),


    #CRUD VIEWS
    path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>', views.updatePost, name="update_post"),
]

myPortofolio/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    sub_title = models.CharField(max_length=200)
    body = RichTextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    thumbnail = models.ImageField(null=True, blank=None, upload_to="images", default="placeholder.png")
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.title)

            has_slug = Post.objects.filter(slug=slug).exists()

            count = 1

            while has_slug:
                count += 1
                slug = slugify(self.title) + '-' + str(count)

                has_slug = Post.objects.filter(slug=slug).exists()
            
            self.slug = slug
        super().save(*args, **kwargs)
    

base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    
    class Meta:
        model = Post
        fields = '__all__'

    widgets = {
        'tags': forms.CheckboxSelectMultiple(),
    }

base/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Post
from .filters import PostFilter
from .forms import PostForm
# Create your views here.

def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]

    context = {'posts':posts}

    return render(request,'base/index.html', context)

def posts(request):
    posts = Post.objects.filter(active=True)
    postFilter = PostFilter(request.GET,queryset=posts)
    posts = postFilter.qs

    page = request.GET.get('page')

    paginator = Paginator(posts,3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts':posts, 'postFilter':postFilter}
    return render(request,'base/posts.html', context)

def post(request, slug):
    post = Post.objects.get(id=slug)
    context = {'post':post}
    return render(request,'base/post.html', context)

def profile(request):
    return render(request,'base/profile.html')

#CRUD VIEWS
@login_required(login_url="home")
def createPost(request):
    form = PostForm()

    # if the request made is post, then we need to process the form
    if request.method == 'POST':

        # create a form instance and populate it with the data from the request
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

        return redirect('posts')

    context = {'form':form}

    return render(request,'base/post_form.html', context)


def updatePost(request,slug):
    post = Post.objects.get(id=slug)
    form = PostForm(instance=post)


    # if the request made is post, then we need to process the form
    if request.method == 'POST':

        # create a form instance and populate it with the data from the request
        form = PostForm(request.POST, request.FILES,instance=post)

        if form.is_valid():
            form.save()

        return redirect('posts')

        context = {'form':form}

        return render(request,'base/post_form.html', context)

@login_required(login_url="home")
def deletePost(request):
    post = Post.objects.get(id=slug)

    if request.method == 'POST':
        post.delete()
        return redirect('posts')

    context = {'item':post}
    
    return render(request,'base/delete.html', context)

base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="main-container">
    <form action="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{item}} </p>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>

</div>

{% endblock content %}

base/templates/base/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    
</body>
</html>

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
{% load icons %}


<html>

<head>
  <title>Hi, I am Hasan Al Banna</title>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "UA-47692315-56");
  </script>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Open+Sans:wght@300;400;700&display=swap"
    rel="stylesheet" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}" />
  <link id="theme-style" rel="stylesheet" type="text/css" href="" />
</head>

<body>
  <section class="s1">
    <div class="main-container">
      <div class="greeting-wrapper">
        <h1>Hi, I'm Hasan Al Banna</h1>
        <h2 class="about-me-title">Computer Engineer . Software Engineer . Fullstack Developer</h2>

        {% icon 'edit' %}
        <button onclick="topFunction()" id="myBtn" title="continue">Scroll down</button>

      </div>

      <div class="intro-wrapper" id="intro-wrapper">
        {% include 'base/navbar.html' %}


        <div class="left-column">
          <img id="profile_pic" src="{% static 'images/Hasan.jpg' %}" />
          <h5 style="text-align: center; line-height: 0">
            Personalize Theme
          </h5>

          <div id="theme-options-wrapper">
            <div data-mode="light" id="light-mode" class="theme-dot"></div>
            <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
            <div data-mode="green" id="green-mode" class="theme-dot"></div>
            <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
          </div>

          <p id="settings-note">
            *Theme settings will be saved for<br />your next vist
          </p>
        </div>

        <div class="right-column">

          <h3 class="about-me-title">A Little About Myself</h3>
          <p class="about-me-paragraph" id="about-me-content">
            An enthusiastic Computer Engineering student that excel in today’s
            technical skills as well as soft skills and is looking to
            contribute in roles where there exist an opportunity for learning
            and self development, to further improve skills through working
            collaboratively with other experienced team members, integrating
            the latest in-demand technical skills with soft-skill, mainly
            within business scope in order to create value and to ship
            reliable software applications.
          </p>
        </div>
      </div>
    </div>
  </section>

  <section class="s2">
    <div class="main-container">
      <div class="about-wrapper">
        <div class="about-me">
          <h4>TOP EXPERTISE</h4>

          <div id="skills">
            <ul>
              <li>Python</li>
              <li>Django</li>
              <li>JavaScript</li>
              <li>React</li>
              <li>Postgres</li>
            </ul>

            <ul>
              <li>Google Maps API</li>
              <li>JS Charts</li>
              <li>AWS (RDS/S3)</li>
              <li>Heroku</li>
              <li>HTML/CSS</li>
            </ul>
          </div>
          <p>
            Fullstack developer with primary focus on Django + React:
            <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a>
          </p>
        </div>

        <div class="social-links">
          <h4 class="section2-title">Check my other social medias</h4>
          <div class="logo--grid">
            <a class="logo-link" href="https://www.linkedin.com/in/hasan-al-banna-836240205">
              <img id="linkedin--logo" src="{% static 'images/Linkedin_logo.png' %}" />
            </a>
            <a class="logo-link" href="https://github.com/albannablade123">
              <img id="github--logo" src="{% static 'images/Github_logo.png' %}" />
            </a>
            <a class="logo-link" href="https://github.com/albannablade123">
              <img id="twitter--logo" src="{% static 'images/Twitter_logo.png' %}" />
            </a>
            <a class="logo-link" href="https://leetcode.com/albannablade123/">
              <img id="leetcode--logo" src="{% static 'images/Leetcode_logo.png' %}" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="s1">
    <div class="main-container">
      <h3 style="text-align: center">Some of my past projects</h3>

      <div class="post-wrapper">
        {% for post in posts %}
        <div>
          <div class="post">
            <img class="thumbnail" src="{{post.thumbnail.url}}" />
            <div class="post-preview">
              <h6 class="post-title">{{post.headline}}</h6>
              <p class="post-intro">{{post.sub_headline}}</p>
              <a href="{%  url 'post' post.id %}">Read More</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      <p align="center">
        <a href="{% url 'posts' %}">View More</a>
      </p>
    </div>
  </section>

  <section class="s2">
    <div class="main-container-education">
      <h4 class="education-title">Education</h4>
      <div class="about-wrapper-education">
        <div class="about-me">

          <div class="education-information">
            <img class="agu-logo" src="{% static 'images/agu_logo.png' %}" />
            <div>
              <h5>Abdullah Gül University</h5>
              <h6>Bachelor of Engineering - BE, Computer Engineering</h6>
              <p>Sep 2019 - Jul 2023</p>
            </div>
          </div>
        </div>

        <div class="courses--taken">
          <div id="skills">
            <ul>
              <li>Database Management</li>
              <li>Object-Oriented Programming</li>
              <li>System Programming</li>
              <li>Data Structures and Algorithm</li>
              <li>Mobile Programming</li>
              <li>Operating System</li>
              <li>Postgres</li>
            </ul>

            <ul>
              <li>Software Engineering</li>
              <li>Analysis of Algorithm</li>
              <li>Computer Networks</li>
              <li>Parallel Architecture </li>
              <li>HTML/CSS</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="s2">
    <div class="main-container">
      <a href=""></a>
      <h3 style="text-align: center">Get In Touch</h3>

      <form id="contact-form" method="POST" action="">
        {% csrf_token %}
        <a name="contact"></a>

        <label>Name</label>
        <input required class="input-field" type="text" name="name" />

        <label>Subject</label>
        <input required class="input-field" type="text" name="subject" />

        <label>Email</label>
        <input required class="input-field" type="text" name="email" />

        <label>Message</label>
        <textarea required class="input-field" name="message"></textarea>

        <input id="submit-btn" type="submit" value="Send" />
      </form>
    </div>
  </section>

  <script type="text/javascript">
    let static = "{% static 'css' %}";


  </script>

  <script>
    mybutton = document.getElementById("myBtn");
    const element = document.getElementById("intro-wrapper");

    function topFunction() {
      element.scrollIntoView({
        block: 'end',
        behavior: 'smooth'
      });
    }

  </script>

  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

</html>

base/templates/base/main.html
<!DOCTYPE html>

{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
    <title>Hasan Al Banna</title>
</head>
<body>
    {% include 'base/navbar.html' %}
    {% include_material_icons %}
    {% block content %}
    {% endblock content %}
    
</body>
</html>

base/templates/base/navbar.html
{% load static %}
<div class="nav-wrapper">

	<!-- Link around dots-wrapper added after tutorial video -->
	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>
			<div id="dot-2" class="browser-dot"></div>
			<div id="dot-3" class="browser-dot"></div>
		</div>
	</a>
	

	<ul id="navigation">
		<h2  id="close-btn" style="text-align: center">X</h2>
		<li><a href="{% url 'home' %}#contact">Contact</a></li>
		{% if request.user.is_authenticated %}
			<li><a> Account</a></li>
			<li><a>Logout</a></li>
		{% else %}
			<li><a>Login</a></li>
		{% endif %}
	</ul>

	<img id="menu-icon" src="{% static 'images/menu.png' %}">

</div>


<script type="text/javascript">
	let menu = 'closed' 

	let menuIcon = document.getElementById('menu-icon')
	let navigation = document.getElementById('navigation')
	let closeBtn = document.getElementById('close-btn')

	menuIcon.addEventListener('click', toggleMenu)
	closeBtn.addEventListener('click', toggleMenu)


	function toggleMenu(){
		if (menu == 'closed'){
			navigation.style.display = 'block'
			closeBtn.style.display = 'block'
			menu = 'open'
		}else{
			navigation.style.display = 'none'
			closeBtn.style.display = 'none'
			menu = 'closed'
		}
	}

	    
	// Attaching the event listener function to window's resize event
	
	window.addEventListener("resize", function(){
		let width = document.documentElement.clientWidth;
		if(width > 1080){
				navigation.style.display = 'block'
		}else{
				navigation.style.display = 'none'
		}
		menu = 'closed'
		closeBtn.style.display = 'none'
	});
	
</script>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
	}

	.post-container{
			width: 900px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin: 2px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50%;
		margin-right: 10px;
	}

	.comment-body{

		font-size: 14px;
	}

	@media screen and (max-width: 900px){
		.post-container{
			width: 95%;
		}
	}
</style>

<div class="post-container">

	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	

	<img class="featured_image" src="{{post.thumbnail.url}}">

	{% for tag in post.tags.all %}
		<span class="tag">{{tag}}</span>
	{% endfor %}
	<hr>

	<h1>{{post.title}}</h1>
	<h4>{{post.sub_title}}</h4>
	<br>

	<p>{{post.body|safe}}</p>

	<div class="comments-wrapper">
		<h5>Comments: {{post.postcomment_set.all.count}}</h5>
		<hr>
		<!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username 
		-->
		{% if request.user.is_authenticated %}
		<form action="" method="POST">
			{% csrf_token %}
			<textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
			<br>
			<input class="btn btn-info" type="submit" value="Submit">
		</form>
		{% else %}
			<p>Create an account to comment:</p>
		{% endif %}

		<hr>
		{% for comment in post.postcomment_set.all %}
			<div class="comment">
				<img class="author-pic" src="{{comment.author.profile_pic.url}}">
				<div>
					<p class="comment-author">{{comment.author}}: {{comment.created|date:"M-d-Y"}}</p>
					<p class="comment-body">{{comment.body}}</p>
				</div>
			</div>
		{% endfor %}
	</div>
</div>


{% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
	#div_id_tags > div{
		max-height: 100px;
		overflow-y: scroll;
		border:1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}
</style>
<div class="main-container">
	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.media}}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" value="Submit Post">
		
	</form>
</div>

{% endblock content %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		max-width: 550px;
		padding: 5px;
		border:1px solid #888;
	}
</style>

<div class="main-container">
	<h1>Projects</h1>
	<form id="searchForm" method="GET">
		{{postFilter.form}}
		<input class="btn btn-primary" type="submit" value="search">
	</form>
	<br>
	<div class="post-wrapper">

		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h6 class="post-title">{{post.title}}</h6>
					<p class="post-intro">{{post.sub_title}}</p>
					<a href="{% url 'post' post.id %}">Read More</a>
					
					{% if request.user.is_authenticated %}
						<a href="{% url 'update_post' post.id %}">Edit Project</a>
					{% endif %}
					<hr>
					{% for tag in post.tags.all %}
					<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr>
				</div>
			</div>
		</div>
		{% empty %}
			<h3>No posts found...</h3>
		{% endfor %}
	</div>
	
	<div class="row">
		
		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}
					
				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>

</div>


<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>

{% endblock content %}

base/templates/base/profile.html
{% extends 'base/main.html' %}

{% block content %}
<h1>Profile</h1>

{% endblock content %}